"""initial migration

Revision ID: 994718c6c38e
Revises: 
Create Date: 2024-03-20 00:30:55.306372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994718c6c38e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
